<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="com.target.myRetail.command.SavePriceDetailsCommandSpec" tests="3" skipped="0" failures="0" errors="0" timestamp="2022-02-27T19:02:14" hostname="MACC02WP14NHTD7" time="0.007">
  <properties/>
  <testcase name="Execute" classname="com.target.myRetail.command.SavePriceDetailsCommandSpec" time="0.004"/>
  <testcase name="PostProcess" classname="com.target.myRetail.command.SavePriceDetailsCommandSpec" time="0.002"/>
  <testcase name="HandleException" classname="com.target.myRetail.command.SavePriceDetailsCommandSpec" time="0.001"/>
  <system-out><![CDATA[13:02:14.327 [Test worker] INFO com.target.myRetail.command.SavePriceDetailsCommand - step=SAVE_PRICE_DETAILS, status=SUCCESS
13:02:14.329 [Test worker] ERROR com.target.myRetail.command.SavePriceDetailsCommand - step=SAVE_PRICE_DETAILS, status=FAIL
]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
